services:
  milvus:
    image: milvusdb/milvus:v2.4.13
    container_name: milvus-standalone
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./configs/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    command: ["milvus", "run", "standalone"]
  setup:
    build:
      context: .
      dockerfile: data_builder/Dockerfile
    container_name: setup_milvus
    environment:
      - MILVUS_HOST=milvus
    depends_on:
      - milvus
    restart: no
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MILVUS_HOST=milvus
    depends_on:
      - milvus
    restart: always
